language: python
python:
    - "2.7"

sudo: false
cache:
    directories:
        - "~/.platformio"

env:
    - PLATFORMIO_CI_SRC=examples/MovingAverageFloat

install:
    - pip install -U platformio
    - platformio update

script:
    - platformio ci --lib="." --board=uno --board=esp01_1m
